// Regenerates src/lib/legal/drafts.ts from the counsel text drafts in docs/legal so production has them without the filesystem.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
const here = dirname(fileURLToPath(import.meta.url));
const legal = resolve(here, '../../../docs/legal');
const read = (f) => (existsSync(resolve(legal, f)) ? readFileSync(resolve(legal, f), 'utf8') : '');
const rules = read('02_Official_Rules_DRAFT.txt'); const terms = read('03_Platform_Terms_of_Service_DRAFT.txt');
if (!rules || !terms) { console.error('docs/legal drafts not found'); process.exit(1); }
const out = `// Generated by scripts/sync-legal.mjs from docs/legal — do not edit by hand.\n/** Counsel draft: Official Rules (bracketed placeholders pending). */\nexport const OFFICIAL_RULES_DRAFT = ${JSON.stringify(rules)};\n/** Counsel draft: Platform Terms of Service. */\nexport const TERMS_DRAFT = ${JSON.stringify(terms)};\n`;
writeFileSync(resolve(here, '../src/lib/legal/drafts.ts'), out);
console.log(`drafts.ts written: rules ${rules.length} chars, terms ${terms.length} chars`);
